import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavbarShell from "@/components/navbar/NavbarShell";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import GsapProvider from "@/components/gsap/GsapProvider";

config.autoAddCss = false;

const roobert = localFont({
  src: [
    { path: "../public/fonts/local/roobert/RoobertPRO-Light.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/local/roobert/RoobertPRO-Regular.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/local/roobert/RoobertPRO-Medium.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/local/roobert/RoobertPRO-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-sans",
  display: "swap",
});

const RoobertTrial = localFont({
  src: [
    { path: "../public/fonts/local/RoobertTrial/RoobertTrial-Light.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/local/RoobertTrial/RoobertTrial-Regular.otf", weight: "500", style: "normal" },
    { path: "../public/fonts/local/RoobertTrial/RoobertTrial-Medium.otf", weight: "600", style: "normal" },
    { path: "../public/fonts/local/RoobertTrial/RoobertTrial-Bold.otf", weight: "700", style: "normal"},
  ],
  variable: "--font-sans-trial",
  display: "swap",
});


const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">

      <body className={`${roobert.variable} ${geistMono.variable} antialiased ` }>
       <NavbarShell>
        <Navbar />
      </NavbarShell>
         <GsapProvider>{children}</GsapProvider>
        <Footer/>
      </body>
    </html>
  );
}
